language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install BeautifulSoup six nose coverage python-coveralls; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install BeautifulSoup4 six nose coverage python-coveralls; fi

script:
  - nosetests

after_success:
  - coveralls
