language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install BeautifulSoup six nose coverage; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install BeautifulSoup4 six nose coverage; fi

script:
  - nosetests
